### PR TITLE
Dev Branch with server, styling and the index

### PR DESCRIPTION
**Pull request by sidon59**
DESCRIPTION:

DEV branch

- The 2 branches were not up to date with each other
-  i was forced to merge earlier in order to avoid future conflicts

Resolutions : 
- After merging i was able to continue with the dev branch due to the realized mistake thus the commits were made to the main branch not the dev hence the conflicts.

Running the project:
-A readme.md file has been added on how to clone and run the project

### CODE REVIEW

**Review by Rabianzo — CHANGES_REQUESTED** [review]
Please add a detailed README file in your repository.

**Comment by sidon59** [comment]
> Please add a detailed README file in your repository.

@Rabianzo yes, i did not do the readMe as yet.

**Review by LundiLanga — CHANGES_REQUESTED** [review]
Your To-Do-List looks good, I like the colors you used and everything is working fine.

What I think you can add is to make the textbox sticky so that when you have a lot of tasks and you are scrolling down it doesn't hide.

With the colors for professional and personal on listed tasks you can also use maybe other colors or just change one because with red and pink it's a little bit hard to tell the difference.

**Comment by sidon59** [comment]
@LundiLanga ok,  i changed the colour for the personal and professional. Will work on the other changes now.

**Comment by sidon59** [comment]
image
Screenshot (27)

@LundiLanga Please help with colours,

**Review by sidon59 — COMMENTED** [review]
fixed

**Review by LundiLanga — COMMENTED** [review]
I see the changes it looks good.

**Comment by Rabianzo** [comment]
> image Screenshot (27)
> 
> @LundiLanga Please help with colours,

**Comment by Rabianzo** [comment]
Your colours are great, the transparent central container is a nice touch. Well done.

**Comment by Rabianzo** [comment]
Please add a title & description to this pull request

**Comment by sidon59** [comment]
> Please add a title & description to this pull request

Noted

**Comment by sidon59** [comment]
@Rabianzo i added a readme.md
Kindly check


Thanks.

**Review by LundiLanga — APPROVED** [review]

**Comment by sidon59** [comment]
@Rabianzo a description has been added

**Review by Rabianzo — APPROVED** [review]
Your README file is well detailed & makes it simple to run your project, well done.

**Comment by Rabianzo** [comment]
> @Rabianzo a description has been added

Your description is well documented, thank you for adding the resolution. Well done.

**Pull request merged**
